import React from 'react';
import Link from 'next/link';

interface ReviewsProps {
  reviewsDue?: number;
}

export default function Reviews({ reviewsDue = 0 }: ReviewsProps) {
  return (
    <div className="flex items-center justify-center p-4 font-sans h-full">
      <div className="w-full max-w-lg">
        <div className="flex justify-center">
          <Link 
            href="/review" 
            // Using semantic utility classes generated by tailwind.config.ts
            className="
              group relative flex w-full max-w-[480px] cursor-pointer flex-col overflow-hidden rounded-2xl 
              border-2 border-shodo-ink/10 bg-shodo-paper p-6 
              transition-all duration-200 
              hover:border-shodo-ink hover:shadow-md 
              active:scale-[0.99] active:shadow-sm
            "
          >
            <div className="flex flex-wrap items-center justify-center gap-6 sm:flex-nowrap">
              
              {/* Image Container */}
              <div className="flex shrink-0 basis-[120px] items-center justify-center">
                <div className="relative flex w-full items-center justify-center">
                  <img 
                    src="/chibi-inkpot-learning.png" 
                    alt="Review Illustration" 
                    className="aspect-square w-full object-contain drop-shadow-md transition-transform duration-300 group-hover:scale-105" 
                  />
                </div>
              </div>

              {/* Content Container */}
              <div className="flex grow flex-col gap-1 text-center sm:text-left">
                
                {/* Header Line */}
                <div className="text-sm font-medium tracking-wider text-shodo-ink/60">
                  You have
                </div>
                
                {/* Main Title + Badge */}
                <div className="flex flex-wrap items-center justify-center gap-3 sm:justify-start">
                  <div className="text-4xl font-bold text-shodo-ink">
                    Reviews
                  </div>
                  <span className="inline-flex h-8 min-w-[2rem] items-center justify-center rounded-full bg-shodo-ink px-3 text-sm font-bold text-shodo-paper shadow-sm transition-transform group-hover:scale-110">
                    {reviewsDue}
                  </span>
                </div>

                {/* Description */}
                <div className="mt-2 text-sm leading-relaxed text-shodo-ink/80">
                  <p className="m-0">
                    Do your <span className="font-semibold text-shodo-ink decoration-dotted underline-offset-4 group-hover:underline">Reviews</span> to advance your learning.
                  </p>
                </div>
              </div>

            </div>
          </Link>
        </div>
      </div>
    </div>
  );
}